python :
  python_path : '~/anaconda/envs/aibs_py35/bin/' # path to anaconda python
data :
  dat_dir : 'spike_finder_data/' # spikefinder data directory
  fps : 100 # frames per second
optimization :
  grid_size : 50 # number of fits for each of l0 and l1 fits
  l0 :
    min_lam : 0.1
    max_lam : 100
    min_cal_conc : 1e-4
  l1 :
    min_lam_log : -3
    max_lam_log : 2.5
    n_threshold : 5
    min_threshold : 1e-8
    max_threshold : 0.5
evaluation :
  vp_cost : 10
  vr_timescale : 0.1
  cor_downsample : 25 # fps
output:
  file_directory : 'experiments/fig5/'
  local_directory : 'experiments/fig5/results'
  figure_directory : 'figures/'


